#pragma once

// SPRITE ENUMS //
enum SPRITE_SIZES {CHAR_DEFAULT_WIDTH = 64, CHAR_DEFAULT_LENGTH = 64};
enum CHAR_SPRITE_ANIMATION_STATES {A_IDLE, A_WALK, A_RUN, A_JUMP};
enum CHAR_SPRITE_PRIMARY_STATES {P_IDLE, P_WALK, P_RUN, P_DODGING};
enum CHAR_SPRITE_SECONDARY_STATES {S_NONE, S_JUMP};
enum SPRITE_TYPES {SPR_CHARACTER, SPR_SHADOW, SPR_RUN_EFFECT, SPR_LAND_EFFECT};
enum EFFECTS {EFF_RUN_EFFECT, EFF_LAND_EFFECT};

// CHARACTER ENUMS // 
enum CHARACTERS {SCOTT, RAMONA, KIM, STEPHEN};

// BACKGROUND ENUMS //
enum BACKGROUNDS {FROZEN_SUBURBS};
enum CHUNKS {LEFT, RIGHT};